_wandb:
    value:
        cli_version: 0.21.1
        code_path: code/algos/baseline_idqn.py
        e:
            bxc88lh5ld8lalafes63nqza3onsvz4e:
                args:
                    - --seed
                    - "1"
                    - --env_id
                    - Dec_Ablaincourt_Floris
                    - --total_timesteps
                    - "150000"
                    - --track
                    - --save_model
                    - --wandb_project_name
                    - benchmark-wfcrl-test
                codePath: algos/baseline_idqn.py
                cpu_count: 14
                cpu_count_logical: 20
                disk:
                    /:
                        total: "1006450962432"
                        used: "239214714880"
                email: Reubenpt123@gmail.com
                executable: /home/reuben/miniconda3/envs/wfcrl/bin/python
                git:
                    commit: e6e4a50700f86d6626341bd7fc0e7efd307a1a4c
                    remote: git@github.com:Reubenpt123/wfcrl-benchmark.git
                host: reuben-uni
                memory:
                    total: "33322377216"
                os: Linux-6.8.0-83-generic-x86_64-with-glibc2.39
                program: /home/reuben/code/wfcrl-benchmark/algos/baseline_idqn.py
                python: CPython 3.11.13
                root: /home/reuben/code/wfcrl-benchmark/scripts
                startedAt: "2025-09-25T10:58:11.167553Z"
                writerId: bxc88lh5ld8lalafes63nqza3onsvz4e
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
                - 34
            "4": 3.11.13
            "5": 0.21.1
            "12": 0.21.1
            "13": linux-x86_64
batch_size:
    value: 128
buffer_size:
    value: 10000
cuda:
    value: true
debug:
    value: false
debug_log:
    value: false
device:
    value: cpu
end_e:
    value: 0.05
env_id:
    value: Dec_Ablaincourt_Floris
exp_name:
    value: baseline_idqn
exploration_fraction:
    value: 0.5
freq_eval:
    value: 50
gamma:
    value: 0.99
hidden_layer_nn:
    value:
        - 64
learning_rate:
    value: 0.00025
learning_starts:
    value: 10000
load_coef:
    value: 1
num_agents:
    value: 7
num_envs:
    value: 1
pretrained_models:
    value: ""
reward_shaping:
    value: ""
save_model:
    value: true
scenario:
    value: constant
seed:
    value: 1
start_e:
    value: 1
target_network_frequency:
    value: 500
tau:
    value: 1
torch_deterministic:
    value: true
total_timesteps:
    value: 150000
track:
    value: true
train_frequency:
    value: 10
wandb_entity:
    value: ""
wandb_project_name:
    value: benchmark-wfcrl-test
wind_data:
    value: /home/reuben/code/wfcrl-benchmark/data/smarteole.csv
