anneal_lr: true
batch_size: 2048
clip_coef: 0.2
clip_vloss: true
cuda: true
debug_log: false
device: !!python/object/apply:torch.device
- cpu
ent_coef: 0.0
env_id: Dec_Ablaincourt_Floris
episode_length: 10
exp_name: baseline_ippo
fine_tuning_freeze: false
freq_eval: 5
gae_lambda: 0.95
gamma: 0.99
hidden_layer_nn: !!python/tuple
- 64
- 64
learning_rate: 0.0003
load_coef: 1
max_grad_norm: 0.5
minibatch_size: 64
norm_adv: true
num_agents: 7
num_iterations: 73
num_minibatches: 32
num_steps: 2048
policy: base
pretrained_models: null
reward_shaping: ''
save_model: true
scenario: constant
seed: 1
torch_deterministic: true
total_timesteps: 150000
track: false
update_epochs: 10
vf_coef: 0.5
wandb_entity: ''
wandb_project_name: benchmark-wfcrl-test
wind_data: data/smarteole.csv
